#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

PROG=/usr/bin/caddy
CONF=/etc/caddy/Caddyfile
PIDFILE=/var/run/caddy.pid

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" run --config "$CONF"
	procd_set_param pidfile "$PIDFILE"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal caddy SIGUSR1
}
